spring:
  datasource:
    url: jdbc:mysql://192.168.245.129:3306/learn
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml